### ISSUE TITLE
Running in Development

### ISSUE THREAD

**Issue by jellybob** [ajmurmann/resque-heroku-autoscaler#1]
I don't see anything in the documentation abou running in development mode, and don't see any indications that it's handled in the code. I'm currently only extending my workers in environments that are running on Heroku, but it would be great if there were a more graceful way of handling that, maybe by being able to set a disabled boolean on the config.

If that were set then the plugin could just log what it would have done, rather then attempting to scale up the workers on my live applications just because I queued a job on my development machine.

I'm very happy to write a patch to implement that if it's of interest, but I just want to check I've not missed anything obvious first.

**Comment by ajmurmann** [comment]
In my own app I have an initializer that monkey patches the set_workers method to just write a log message:

```
if (Rails.env == 'development')
  class Heroku::Client
    def set_workers
      Rails.logger.info("Skipping start of worker because app is in dev modus")
    end
  end
end
```

However, that's a pretty ugly solution for a probably very common problem. So I will add an option in the config for his.

**Comment by ajmurmann** [comment]
I just pushed a new version that should solve your problem. Please let me, if this solution works for you!

**Comment by jellybob** [comment]
That looks great, thanks!
